# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := slic
CLASSNAMES := sliceplay~ slicerec~


################################################################################


include ../includes/libbuildrules.mk
