# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := verbkit
CLASSNAMES := combsL~ combsR~ damp~ dcombsL~ dcombsR~ diffusorL~ diffusorR~ 


################################################################################


include ../includes/libbuildrules.mk
