# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := dyna
CLASSNAMES := complexify~ duck~ instantamp~ qompand~


################################################################################


include includes/libbuildrules.mk
