# GNU make / gcc Makefile for building Pd lib / project

# Build targets and rules are defined in ../includes/libbuildrules.mk


################################################################################


LIBNAME := crip
CLASSNAMES := bitflip~ krunch~ 


################################################################################


include ../includes/libbuildrules.mk
